---
name: archiva

releases:
- name: apache-archiva
  version: "v2"
  url: "https://github.com/a2geek/apache-archiva-bosh-release/releases/download/v2/apache-archiva-bosh-release.tgz"
  sha1: "fbf72f4260bbf9a88657124769f32333d67dda6e"
- name: "bpm"
  version: "1.1.6"
  url: "https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.1.6"
  sha1: "5bad6161dbbcf068830a100b6a76056fe3b99bc8"

instance_groups:
- name: archiva
  instances: 1
  vm_type:   default
  stemcell:  default
  azs:       [z1]
  networks:
  - name:    default
  persistent_disk: 10240
  jobs:
  - name:    archiva
    release: apache-archiva
    properties:
      bpm:
        enabled: true
  - name: bpm
    release: bpm

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 5000-60000
  update_watch_time: 5000-60000

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest